{% set name = "asdf-astropy" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_astropy-{{ version }}.tar.gz
  sha256: c568c4706800cf5ab439d012b6b3258079321505cbd33d027b95f14789b6f161

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - asdf >=2.8.0
    - asdf-coordinates-schemas
    - asdf-transform-schemas >=0.2.2
    - astropy >=5.0.4
    - importlib-resources >=3
    - numpy
    - packaging >=16.0
    - python >=3.8

test:
  imports:
    - asdf_astropy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/astropy/asdf-astropy
  summary: ASDF serialization support for astropy
  license: BSD-3-Clause
  license_file: licenses/LICENSE.rst

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
